- name: Update and upgrade all hosts in the inventory file
  hosts: allhosts
  tasks:
    - name: Append custom parameters to cmdline.txt
      become: true
      command: sed -i "1 s|$| logo.nologo consoleblank=0 loglevel=0 vt.global_cursor_default=0 splash silent quiet|" /boot/firmware/cmdline.txt

    - name: Use custom config.txt
      become: true
      copy:
        dest: /boot/firmware/config.txt
        src: ../overlay/boot/firmware/config.txt

    - name: Ensure fluxbox configuration directory exists
      file: 
        path: ~/.fluxbox
        state: directory

    - name: Copy fluxbox startup configuration
      copy:
        dest: ~/.fluxbox/startup
        src: ../overlay/home/berrycells/.fluxbox/startup

    - name: Copy fluxbox menu configuration
      copy:
        dest: ~/.fluxbox/menu
        src: ../overlay/home/berrycells/.fluxbox/menu

    - name: Copy fluxbox init configuration
      copy:
        dest: ~/.fluxbox/init
        src: ../overlay/home/berrycells/.fluxbox/init

    - name: Make sure there is no lastwallpaper file
      ansible.builtin.file:
        path: ~/.fluxbox/lastwallpaper
        state: absent

    - name: Copy berrycell background image to home folder
      copy:
        dest: ~/splash.png
        src: ../overlay/usr/share/plymouth/themes/pix/splash.png

    - name: Set fluxbox background image
      environment:
          DISPLAY: ":0.0"    
      command: fbsetbg -f /home/berrycells/splash.png

    - name: Disable tty1
      become: true
      command: "sudo systemctl disable --now getty@tty1"

    - name: Reboot the machine
      become: true
      ansible.builtin.reboot:
        msg: "Rebooting machine in 5 seconds"