class BerryConfiguration():
    deviceid = 17                               # Device id; only packages coming from this id will be processed
    udp_ip = "192.168.15.2"                     # Local IP
    udp_fip = ["192.168.15.9","192.168.15.10"]  # Forward IP
    forwardUdp = True                           # forward udp packages to other IP or not
    mode = 'udp'                                # udp or serial
    showQrCode = False                          # show QR code as option if you do not want to print the sticker
    fullscreen = True
    saveCsv = False                             # Save CSV measurement data
    liveCsv = False                             # Continuously save the csv file
    ignoreKeypress = False                      # Ignore keyboard events
    uploadToSunetDrive = False                  # Upload live.csv to Sunet Drive via webdav
    publishWithRDS = False                      # publish with RDS for TNC24
    publicationScript = "~/sunet/drive-tests/sandbox_tnc_publication.py"
    doifile = '~/sunet/drive-tests/tncdoi.txt'
    printrendertime = False
    printSticker = False
    uploadToGoogle = False
    usemovingaverage = False
    mavalues = 3                                # How many values to consider for moving average
    udptimeout = 10.0                           # depends on dwell time
    serialtimeout = 0.5
    udpbuffersize = 256
    currentCell = 1
    scaleWidth = 576                            # scalewidth for print 576 for PeriPage, 696 for QL-810W
    printerType = 'brother'                     # peripage or brother
    printerMac = '20:20:08:1b:3a:1a'            # PeriPage
    printeridentifier = 'tcp://192.168.15.5'    # Brother Network Print
    comport = 'COM5'
    xmax = 1.0                                  # xmax value until we have autoscaling
    ymax = 1.0                                  # ymax value until we have autoscaling